### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by GiovanniKaaijk** [cmda-bt/be-course-18-19#115]
# Listing

## Name
Giovanni Kaaijk

## Class
Tech 4

## Repo link
https://github.com/GiovanniKaaijk/project-tech

## Summary
I made 3 basic pages with partials, used express to send back html and static files.

## Resources used
Express

## Any thoughts?
-

**Comment by rijkvanzanten** [comment]
Heya 👋 

* Remove `.DS_Store` from the repo
* Expand your readme with useful sections like a description and usage/installation instructions
* What are your thoughts about Pug?
* Remove the `index.html` page. I think it's not used anymore and it's confusing to have in the repo
* The imgSrc variable will be empty while the cat image is loading. While it's loading, users opening your website will be served a page with no image until its done.

https://github.com/GiovanniKaaijk/project-tech/blob/d83e559c9372fd36015615abb8f2ba6c4b3f25b5/server.js#L6-L14

* Not sure if this is what you were trying, but each time a user opens the `/` route, the same cat image is served. Is this intentional, or were you trying to show a different image each time?
