### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by kriskuiper** [cmda-bt/be-course-18-19#22]
# Listing

## Name
`Kris Kuiper`

## Repo link
[Link to my Project Tech repo](https://github.com/kriskuiper/project-tech)

## Summary
`I have built a Express server with a dynamic Front-end by using fake data.`

## Resources used
* [Backend Course example repo](https://github.com/cmda-bt/be-course-18-19/tree/master/examples/express-server) for having an example on how to build a server using Express and how to render data dynamically using EJS.
* [EJS website](https://ejs.co/) for getting a better understanding on what EJS can do exactly and syntax.
* [Stackoverflow](https://stackoverflow.com/questions/24582338/how-can-i-include-css-files-using-node-express-and-ejs) for getting to know how I can use my static css file in the dynamic rendered pages.

## Any thoughts?
`It was just sick! Maybe it would be more difficult if I had used another templating language but I really like the syntax of EJS, it reminds me a bit of developing a Wordpress website.`

**Comment by dandevri** [comment]
After a quick glance it looks good! 👍 

Since you finished quite early, here are some suggestion for things to work on:

* `ejs` is a solid choice, you can try and investigate the other template engines to see if they offer other functionality. In `pug` for example you can use `mixins` and `layouts` instead of just includes.
* See if you can work on the exercise for next week, you render data that's stored in the `index.js` file. Do you think you can already get that data from the client? So the user can manually input that data? So maybe start with encoding a simple form?
* Look at different ways to structure your project, what is server and client side? You can start looking into the [mvc-model](https://www.codecademy.com/articles/mvc) to keep your JS patterns clean.
* Have a look at what `middleware` is and try to incorporate useful middleware packages in your express routes.
