### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/be-course-18-19#32]
# Listing

## Name
`Stefan Gerrits`

## Repo link
[Repo](https://github.com/StefanGerrits2/datingwebsite-bloktech)

## Summary
`I installed express and pug to make a server. There are static files you can request aswell as pug files. I created partials for pug so I can use them in my pug files, for example a header and a footer. Last but not least I started working on the html and css of my website.`

## Resources used
* https://pugjs.org/api/getting-started.html
* https://expressjs.com/
* https://www.npmjs.com/package/pug

## Any thoughts?
`I started working on this assignment before we had the live demo. Trying to figure it out yourself is a pretty good way too learn something! It forced me to trial and error, which taught me a lot. Also I had a little bit of help from the live demo in class ;)`

**Comment by rijkvanzanten** [comment]
> Trying to figure it out yourself is a pretty good way too learn something

Absolutely! Never copy-pasting anything is a good way to practice too 🙂 

* I like your style of putting the route handlers in separate functions, keeps the definition of routes nice and clean. You could consider changing them together, so you don't have to have the `app` on every line:

```js
// from
app.get('/profiel', profiel);
app.get('/matches', matches);
app.get('/inbox', inbox);
app.get('/zoeken', zoeken);

// to
app
  .get('/profiel', profiel)
  .get('/matches', matches)
  .get('/inbox', inbox)
  .get('/zoeken', zoeken);
```

* Try to clean up your javascript a little bit. You switch back and forth between tabs and spaces, have random whitespace at times, switch between using and not-using semi-colons etc etc. Consider installing a linter that warns you about these things!
* Use Pug for building uit the HTML structure instead of doing it manually inline: https://github.com/StefanGerrits2/datingwebsite-bloktech/blob/3cd1250e31b29287103f04eb374acf97e5ed1427/index.js#L45-L60
* Did you work together with @victorlaforga on this? Or is there an online tutorial that shows you how to build up your html in this fashion? I'm asking cause I noticed you both use a surprisingly similar way that I haven't seen anyone else do.

**Comment by StefanGerrits2** [comment]
Hey Rijk,

Thanks for your feedback!

I've just tried removing the `app` on every line, but I get this error message:

/mnt/d/Bestanden Stefan/Desktop/CMD Jaar 2/Project Tech/datingwebsite-bloktech/index.js:18
  .use(bodyParser.urlencoded({extended: true}));
  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)

![](http://i68.tinypic.com/14ilymv.jpg)

Also, at every dot I use except the first one, it has a red line under it. Do you have a clue why this doesn't work for me?

I will start working on building the HTML structure in pug instead of javascript!

And no, I did not work together with @victorlaforga. I think this is a coincidence because I think we both used the slides from the lesson as an example.

**Comment by rijkvanzanten** [comment]
You still have the semicolon `;` at the end of each line 🙂

> And no, I did not work together with @victorlaforga. I think this is a coincidence because I think we both used the slides from the lesson as an example.

Gotcha 👍

**Comment by StefanGerrits2** [comment]
> You still have the semicolon ; at the end of each line 🙂

Right... whoops.

Thanks!
