### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/be-course-18-19#38]
# Listing

## Name
Artemis

## Repo link
[Repository](https://github.com/Kalemis/Listing)

## Summary
I started out with the express-server example. I made some own ejs pages and then adjusted the routing. I tried to display the data from the form on the next page but I couldn't get it to work. Then I found out that it's actually part of next week's assignment, so I tried to conditionally render the login/register page. I think it is easier with pug, so that is something I would like to try next week.

## Resources used
https://expressjs.com/en/resources/middleware/body-parser.html
https://www.npmjs.com/package/nodemon
https://github.com/cmda-bt/be-course-18-19/blob/master/examples/express-server

## Any thoughts?
I liked being able to experiment with includes and ejs. For the next assignment I think I'm going to try pug to see the difference and which of them I prefer.

**Comment by rijkvanzanten** [comment]
Heya! Well done

* Try to pay some more attention to code style and consistency. You seem to switch back and forth between 4 and 2 spaces of indentation
* Is the `/static/home.js` file just to test if it was working? Why add the classes dynamically after the page was loaded instead of in the markup ahead of time?
* As an improvement on the user side, try showing an error to the user on the page instead of [just in the console](https://github.com/Kalemis/Listing/blob/master/static/index.js#L27)
