### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/be-course-18-19#53]
# Data

## Name
Lien Vo

## Repo link
[dating app](https://github.com/nlvo/dating-app)

## Summary
Unfortunately I couldn't get the form to work, but I feel like I'm almost there. However I was able to loop through some test data. And cleaned up my code a bit. I also changed my templating engine from pug to ejs.

## Resources used
- [Body-parser](https://medium.com/@adamzerner/how-bodyparser-works-247897a93b90)
- [Slug](https://www.npmjs.com/package/slug)
- [Scotch](https://scotch.io/tutorials/use-expressjs-to-get-url-and-post-parameters)
- Code examples from the lectures
- Stackoverflow

## Any thoughts?
Before I started this assignment, I thought that it wouldn't be that difficult to get a form to work, but somehow I can't wrap my head around it. But I do feel like I'm almost there so I'll keep working on it.

**Comment by rijkvanzanten** [comment]
Hey there!

What problems did you run into specifically? Don't forget you have direct access to all your classmates who are solving the exact same problems on Slack! There's even professors and people like me there ready to help you out.

Also, part of the problem is that you're trying to create a slug from the `id` field that's being passed `var id = slug(req.body.id).toLowerCase()`. However, based on a quick scan of [your form](https://github.com/nlvo/dating-app/blob/master/views/register.ejs), you don't have an input with `id` as `name`. I think you meant to use [the input with `name='name'`](https://github.com/nlvo/dating-app/blob/master/views/register.ejs#L6) instead:
`var id = slug(req.body.name).toLowerCase()`

Other than that, this is coming together quite nicely 🙂

**Comment by nlvo** [comment]
Hi @rijkvanzanten,

Thanks for pointing that out and also thanks for the feedback. I just found out the real problem... there was technically nothing wrong like you said, but I somehow wrote `methode='POST'` instead of `method`...facepalm.

So in the end there were no problems, just a typo.. anyway everthing works like it should!
